image: google/cloud-sdk:latest

stages:
  - build
  - deploy

variables:
  PROJECT_ID: "deron-innovations"
  REGION: "us-central1"
  REPO: "ai-powered-pdf-table-extractor-repo" # name of the repo in the artifact registry
  REGISTRY: "us-central1-docker.pkg.dev" # registry url
  CLUSTER: "ai-powered-pdf-table-extractor" # name of the cluster in the gke

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 curl bash
    - curl https://sdk.cloud.google.com | bash -s -- --disable-prompts > /dev/null
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - echo "$GCP_SERVICE_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO/llmops-app:latest

deploy_to_gke:
  stage: deploy
  needs:
    - build_docker_image
  before_script:
    - echo "$GCP_SERVICE_KEY" | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud config set project $PROJECT_ID
  script:
    - gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml
  only:
    - main
